import type { BloqueConfig } from "../types/calculator";

export const BLOQUES: BloqueConfig[] = [
  {
    id: "venue",
    label: "Venue",
    desc: "Espacio físico para el evento: salones, terrenos, centros de eventos.",
    icon: "◼",
    costoFijo: [3_000_000, 12_000_000],
    costoPorPersona: [0, 0],
    categoria: "espacio",
  },
  {
    id: "catering",
    label: "Catering",
    desc: "Alimentación y bebidas para los asistentes: coffee, almuerzo, cóctel o cena.",
    icon: "◆",
    costoFijo: [0, 0],
    costoPorPersona: [18_000, 45_000],
    categoria: "gastronomia",
  },
  {
    id: "av_basico",
    label: "AV básico",
    desc: "Sonido, micrófonos, proyector y pantalla. Esencial para cualquier evento.",
    icon: "▲",
    costoFijo: [1_500_000, 3_500_000],
    costoPorPersona: [0, 0],
    categoria: "tecnologia",
  },
  {
    id: "av_premium",
    label: "AV premium",
    desc: "LED wall, pantallas múltiples, sistema de audio profesional de gran alcance.",
    icon: "▲",
    costoFijo: [5_000_000, 15_000_000],
    costoPorPersona: [0, 0],
    categoria: "tecnologia",
  },
  {
    id: "iluminacion",
    label: "Iluminación",
    desc: "Iluminación escénica, ambiental y de efecto para transformar el espacio.",
    icon: "●",
    costoFijo: [1_200_000, 4_000_000],
    costoPorPersona: [0, 0],
    categoria: "tecnologia",
  },
  {
    id: "decoracion",
    label: "Decoración",
    desc: "Montaje visual y elementos decorativos alineados con la identidad de marca.",
    icon: "◈",
    costoFijo: [500_000, 3_000_000],
    costoPorPersona: [0, 0],
    categoria: "espacio",
  },
  {
    id: "fotografia",
    label: "Fotografía",
    desc: "Registro profesional del evento con entrega de galería editada.",
    icon: "○",
    costoFijo: [600_000, 1_500_000],
    costoPorPersona: [0, 0],
    categoria: "contenido",
  },
  {
    id: "video",
    label: "Video corporativo",
    desc: "Cobertura en video y edición de resumen para comunicaciones internas o redes.",
    icon: "○",
    costoFijo: [2_000_000, 6_000_000],
    costoPorPersona: [0, 0],
    categoria: "contenido",
  },
  {
    id: "animacion",
    label: "Animación / MC",
    desc: "Conductor de eventos o animador profesional para mantener el flujo del programa.",
    icon: "◇",
    costoFijo: [500_000, 2_000_000],
    costoPorPersona: [0, 0],
    categoria: "logistica",
  },
  {
    id: "rrhh",
    label: "Staff y azafatas",
    desc: "Personal de apoyo para registro, protocolo y atención en sala.",
    icon: "◇",
    costoFijo: [400_000, 1_200_000],
    costoPorPersona: [3_000, 7_000],
    categoria: "logistica",
  },
  {
    id: "transporte",
    label: "Transporte",
    desc: "Traslado de asistentes, equipos o materiales hacia el venue.",
    icon: "◈",
    costoFijo: [500_000, 3_000_000],
    costoPorPersona: [0, 0],
    categoria: "logistica",
  },
  {
    id: "activacion",
    label: "Activación de marca",
    desc: "Stand interactivo, juego, experiencia o BTL dentro del evento.",
    icon: "◼",
    costoFijo: [2_000_000, 8_000_000],
    costoPorPersona: [0, 0],
    categoria: "espacio",
  },
  {
    id: "streaming",
    label: "Streaming / Híbrido",
    desc: "Transmisión en vivo o grabación para audiencias remotas.",
    icon: "●",
    costoFijo: [1_200_000, 4_000_000],
    costoPorPersona: [0, 0],
    categoria: "tecnologia",
  },
  {
    id: "branding_fisico",
    label: "Branding físico",
    desc: "Impresiones, señalética, credenciales, banners y materiales de marca.",
    icon: "◆",
    costoFijo: [400_000, 1_800_000],
    costoPorPersona: [2_000, 5_000],
    categoria: "contenido",
  },
];

export const BLOQUES_BY_ID = Object.fromEntries(
  BLOQUES.map((b) => [b.id, b])
) as Record<string, BloqueConfig>;
